version: '3'

services:
  app:
    build: .
    volumes:
      - ./:/var/www
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "61386:3306"
    volumes:
      - "./.docker/db:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: uniforca
      MYSQL_ROOT_PASSWORD: rhuniforca

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - mysql
    restart: always
    ports:
      - "81:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1

  nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - "7777:80"
    volumes:
      - ./:/var/www
    depends_on:
      - app
